sudo: false
language: python
python:
  - "2.7"
  - "3.4"
install:
 - pip install -U pip wheel setuptools
 - pip install -r requirements.txt
 - pip install -r test-requirements.txt
script:
 - python -m unittest.__main__ discover
